name = "dmsj-blog"
compatibility_date = "2026-08-01"
pages_build_output_dir = "./dist"

# 上线前把占位 database_id / id 换成你账号下真实资源。
d1_databases = [
  { binding = "DB", database_name = "dmsj-blog-db", database_id = "6736fccc-321d-4cd2-99d4-3b0d7fb73287", migrations_dir = "./drizzle" }
]
kv_namespaces = [
  { binding = "SESSION", id = "7ed04ff9270a436a87737a856e638510" }
]
